### ISSUE TITLE
Wrong Sleep time in ATKDEFMode

### ISSUE THREAD

**Issue by nahuelr** [4RTools/4RTools#110]
**Current behavior:**
Switch delay time is set to `50ms` for the "switch back to def set" step instead to `this.switchDelay`

https://github.com/4RTools/4RTools/blob/afe6fc06e8e47071b6af409db5cb52c6157e1e46/Model/ATKDEFMode.cs#L74

This Value is correct for "switch to ATK set" step.

https://github.com/4RTools/4RTools/blob/afe6fc06e8e47071b6af409db5cb52c6157e1e46/Model/ATKDEFMode.cs#L56

**Expected behavior:**
 "switch back to def set" step should press each key for the DEF set each `this.switchDelay`

**Comment by afonsocdaniel** [comment]
Thank you, @nahuelr!! Do you mind open a PR for this one?

**Comment by markiing** [comment]
@nahuelr 

Are you there?!

**Comment by nahuelr** [comment]
> Thank you, @nahuelr!! Do you mind open a PR for this one?

Sure, i will work on this

**Comment by markiing** [comment]
@nahuelr Any updates?
