### ISSUE TITLE
Autobuff is broken on Ragna4th

### ISSUE THREAD

**Issue by aDwCarrazzone** [4RTools/4RTools#112]
**Describe the bug**
Autobuff is not working anymore.

**Comment by markiing** [comment]
hey @aDwCarrazzone .
Do you have more details? The app shows any message? Apps crash?

Have something?

**Comment by Demnokkoyen** [comment]
Mine was bugged too. I just cloned the repo and rebuilt the project, it's working as intended for me now.

**Comment by markiing** [comment]
Latest version still bugged @Demnokkoyen ?

**Comment by Demnokkoyen** [comment]
I didn't try downloading the latest version available again. I'm compiling with the code thats on `main` branch and it's working as intended this way.
