### ISSUE TITLE
Loop Macro Songs (QoL)

### ISSUE THREAD

**Issue by nahuelr** [4RTools/4RTools#115]
**Is your feature request related to a problem? Please describe.**
QoL: I would like Clown/Gypsy songs can be loop to minimize the keystrokes and ensure buffs are always active

**Describe the solution you'd like**
A Radio Button(to select only one macro song hotkey to loop) to loop a macro so it can ensure songs buff are always active without pushing any key. It free your main of taking into account this buffs and can focus on your main task (this is why this is a QoL). Usefull while making potions(creator/cross), lvling with exp ensemble, farming mushrooms using plant cultivation, or farming mobs with autofollow. (This is why it is a QoL feature)

**Describe alternatives you've considered**

- Macro calling itself setting as the "last song" the key that trigger the whole macro. This doesn't trigger the macro again.
- Macro calling another macro at the end which call the first one at its end. (Same as before but with 2 macros)

**Comment by markiing** [comment]
Hey @nahuelr . 

And how the thread will behave? Today we have only one thread to handle all 4 macro lanes. If we have some macro looping, the thread will be closed for another macros.

Although today we can activate only one macro per time.

**Comment by markiing** [comment]
@nahuelr any updates?
