### ISSUE TITLE
Please Add All Star RO

### ISSUE THREAD

**Issue by uraties** [4RTools/4RTools#116]
Please add:

http://www.allstar-ro.net/ 

  {   
        "name": "AllstarRO",
        "description": "AllstarRO",
        "hpAddress": "0x10DCE10",
        "nameAddress": "0x10D5DA8"
    },
    {
        "name": "AllstarRO",
        "description": "AllstarRO_Alt",
        "hpAddress": "0x10DCE10",
        "nameAddress": "0x10DF5D8"
    }

**Comment by noxnoire** [comment]
already added the pull request , just wait for now

**Comment by markiing** [comment]
See #117
