### ISSUE TITLE
Create a fallback to the supported_servers file, and read the server list from a local file

### ISSUE THREAD

**Issue by afonsocdaniel** [4RTools/4RTools#121]
**Describe the bug**
Asian users sometimes have issues while performing requests to the GitHub to read the `supported_servers.json`, in that case we can read the local file as a fallback.

**To Reproduce**
1. Open 4RTools
2. Block requests to `supported_servers.json`

**Expected behavior**
Setting a timeout or rescue exception when performing a request to the `supported_servers`, once receives an error, instead of stop the application, try to read a local file as a fallback.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by markiing** [comment]
Workin on it.

**Comment by markiing** [comment]
#126
