### ISSUE TITLE
Error when using 4Rtools V.1.8.1

### ISSUE THREAD

**Issue by yhal9239** [4RTools/4RTools#154]
Hi Creators,

I just wanted to report this Error I'm getting when using the 4Rtools.
Is there any way to fix it? 

Thanks for the help! <3

![image](https://user-images.githubusercontent.com/112972321/188698889-699c114e-294a-4ad0-b6e7-a0010e99434f.png)

**Comment by markiing** [comment]
Hello @yhal9239 .

There's some missing `dlls`. NewtonSoft.Json is missing :( did you extract 4R in a folder?

**Comment by yhal9239** [comment]
Hi

No, I did not extract it on a specific folder. I just extract it on
downloads folder.

**Comment by yhal9239** [comment]
Hi

Its working now. Thank you so much for the help!
