### ISSUE TITLE
Create a How-to doc explaining how to add new servers

### ISSUE THREAD

**Issue by afonsocdaniel** [4RTools/4RTools#162]
**Is your feature request related to a problem? Please describe.**
Create a How-to document explaining how to add new servers using the supported server list.
This document should teach how to get the HP memory address and the Character name memory address, and the baby steps to take that information, how to update the `json` file and how to test this on local development.

Can be a markdown file or Wiki.

**References:**
[ArtMoney Game Cheater](https://www.artmoney.ru/)
[Cheatengine](https://www.cheatengine.org/)

**Comment by belli222** [comment]
That would be very good and helpful
