### ISSUE TITLE
Couldn't select my Ragnarok Client (Ragnarok Tab)

### ISSUE THREAD

**Issue by xButaw** [4RTools/4RTools#174]
Hi, I couldn't select my ragnarok client no matter what I do. Can anyone help me fix this? The name of the ragnarok is God War RO. Its fairly new and here is the website http://www.godwarro.com/

**Comment by markiing** [comment]
Hello @xButaw 

This happens because we don't have support for you server. Try to add support by yourself following this 

https://www.youtube.com/watch?v=AH6QtJddd00
