### ISSUE TITLE
please add autobuffs_item SCROLL LINK (talisman scroll)

### ISSUE THREAD

**Issue by bryandakis** [4RTools/4RTools#176]
hello 4rtools

i hope you can add autobuffs of this scroll in your APP.

Thank you!

Server: Arunafeltz RO

**Comment by afonsocdaniel** [comment]
@bryandakis Can you send to us the item ID or a print screen, please?

**Comment by bryandakis** [comment]
> @bryandakis Can you send to us the item ID or a print screen, please?

hello, i can't see the id number but here's the screenshot

![image](https://user-images.githubusercontent.com/81462590/200933684-9ffe1b36-d741-4f83-b078-d4c2b783dc30.png)

**Comment by markiing** [comment]
Done 👍
