### ISSUE TITLE
After closing all programs it still working

### ISSUE THREAD

**Issue by junglejf** [4RTools/4RTools#177]
**Describe the bug**
After closing all rtools apps, the macro still working.
![image](https://user-images.githubusercontent.com/12838919/200335968-97d9f1de-7c41-43f8-b168-1a94633be8d4.png)

How to force windows kill all 4rtools services running on background ?

**Comment by afonsocdaniel** [comment]
@junglejf can you send more details and the steps to reproduce this issue?
Thank you!
