### ISSUE TITLE
help .. how to solve this ?

### ISSUE THREAD

**Issue by Nazringps92** [4RTools/4RTools#196]
after install. click on to start. got this. 
![Untitled](https://user-images.githubusercontent.com/121682062/210087003-2e088f76-4e51-45e5-b4d1-248d5692349e.jpg)

**Comment by markiing** [comment]
Hello @Nazringps92. We don't have official support for Windows 7, but you can try install [NetFramework 4.8](https://support.microsoft.com/pt-br/topic/instalador-offline-do-microsoft-net-framework-4-8-para-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0). Maybe works ;)
