### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by haly-dev** [4RTools/4RTools#200]
what is this ? 

![Screenshot_253](https://user-images.githubusercontent.com/107888695/216866827-25b39296-b354-44a2-b73d-812750adaf14.png)

**Comment by afonsocdaniel** [comment]
This is not a bug, this is necessary since `4RTools` has some code to scan memory address of the Ragnarök process.

**Comment by afonsocdaniel** [comment]
This is not a bug, this is necessary since 4RTools has some code to scan memory address of the Ragnarök process.
