### ISSUE TITLE
How to add my own server?

### ISSUE THREAD

**Issue by jbersamin** [4RTools/4RTools#204]
Is there a guide on how to add my own server with this tool?

**Comment by lumbakennethte-netizen** [comment]
any new discord link please?

**Comment by markiing** [comment]
@lumbakennethte-netizen this link provided by @afonsocdaniel is still valid

**Comment by lumbakennethte-netizen** [comment]
> [@lumbakennethte-netizen](https://github.com/lumbakennethte-netizen) this link provided by [@afonsocdaniel](https://github.com/afonsocdaniel) is still valid

when i click the link sir it goes blank(discord app) sir maybe i dont have access to the channel
