### ISSUE TITLE
Prepare the code to handle different buffsCodeIds when dealing with different servers

### ISSUE THREAD

**Issue by ChristoferDantas** [4RTools/4RTools#24]
**Is your feature request related to a problem? Please describe.**
Currently, your code expects that each buffs/status has a single ID. The id's will vary according to client. For example, you are expecting that STR_FOOD will always be 241, but it will generally go between 201 and 291.

**Comment by afonsocdaniel** [comment]
For this issue, we will provide a base GRF that will complain to every server. Once the user has problem with some status/buff, just download our base GRF. Thank you for the feedback, really appreciate.

**Comment by ChristoferDantas** [comment]
Even though this solution works for some servers, you guys should have in mind that there are servers that lock the edition of lub files
