### ISSUE TITLE
Allow users to put their own delay in autobuff stuffs/skills

### ISSUE THREAD

**Issue by ChristoferDantas** [4RTools/4RTools#42]
**Is your feature request related to a problem? Please describe.**
Today, the autobuff is set hardcoded to work with 100ms.
It might be bad in scenarios where you may get locked, for example, when you are in WoE and are being dispelled. Your character would be stuck trying to use autobuffs.

**Describe the solution you'd like**
The user should be able to set your own delay.

**Comment by Pipole26** [comment]
Yeah this is 100% needed otherwise things like [this](https://cdn.discordapp.com/attachments/804267218539773972/952672236878331924/giphy_1.gif) might happen
