### ISSUE TITLE
Create a reset button for each tab/feature

### ISSUE THREAD

**Issue by ChristoferDantas** [4RTools/4RTools#44]
**Is your feature request related to a problem? Please describe.**
I don't know if profiles can solve this problem, but it can be very tiring having to configure new autobuffs/spammers/autopot if there isn't a button to reset the settings (e.g. deselect all)

**Describe the solution you'd like**
I think a reset button for each tab/autopot might be a good solution to handle a new configuration.

**Comment by afonsocdaniel** [comment]
Additional information: for this issue, we should show a confirmation dialog to prevent from miss click because every change in the inputs, automatically update the profile settings
