### ISSUE TITLE
[EFST_IDs.EFST_HALLUCINATIONWALK] doesnt work as alteraded state because the original effect from data is EFST_ILLUSION.

### ISSUE THREAD

**Issue by Atomixv2** [4RTools/4RTools#74]
Change this part of code to EFST_ILLUSION, that the real effect of Hallucination.

` private void onStatusKeyChange(object sender, EventArgs e)
        {
            Key k = (Key)Enum.Parse(typeof(Key), this.txtStatusKey.Text.ToString());

            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.POISON, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.SILENCE, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.BLIND, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.CONFUSION, k);
            **this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.HALLUCINATIONWALK, k);**
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.CURSE, k);

            ProfileSingleton.SetConfiguration(this.autoEffectStatus);
        }
    }
}`
TO:
`private void onStatusKeyChange(object sender, EventArgs e)
        {
            Key k = (Key)Enum.Parse(typeof(Key), this.txtStatusKey.Text.ToString());

            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.POISON, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.SILENCE, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.BLIND, k);
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.CONFUSION, k);
            **this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.ILLUSION, k);**
            this.autoEffectStatus.AddKeyToBuff(EffectStatusIDs.CURSE, k);

            ProfileSingleton.SetConfiguration(this.autoEffectStatus);
        }
    }
}``

Try to remove Hallucination effect with Panacea, Royal Jelly or GreenPotion and doesnt work, because the code doesnt recognize the real effect id, try to check it, thx.

**Comment by afonsocdaniel** [comment]
Thank you, I'll open a fix for that.
