### ISSUE TITLE
Server Support: https://ragna4th.com/

### ISSUE THREAD

**Issue by aDwCarrazzone** [4RTools/4RTools#80]
Currently the server ragna4th isn't supported.

Using the tool in the server as usual would be great. ;D

**Comment by markiing** [comment]
hey @aDwCarrazzone .

https://github.com/4RTools/4RTools/commit/88d5600fa905723e8c60b71339c1719a9201085a

Just did :)

**Comment by aDwCarrazzone** [comment]
How can i manually compile it to use on the server? ;D Cuzz it isnt working rn with the newest release

**Comment by aDwCarrazzone** [comment]
Just found it xD

**Comment by afonsocdaniel** [comment]
Cool @aDwCarrazzone 👍 Any issues let us know.

att, Authentic
